# Generated by Django 4.2.5 on 2023-11-14 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('due_date', models.DateField()),
            ],
            options={
                'db_table': 'assignment',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('enrollment_capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'course',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('document_type', models.CharField(max_length=150)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.course')),
            ],
            options={
                'db_table': 'material',
                'ordering': ['upload_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_content', models.CharField(max_length=150)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.user')),
            ],
            options={
                'db_table': 'submission',
                'ordering': ['submission_date'],
            },
        ),
        migrations.CreateModel(
            name='ReadingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_state', models.IntegerField()),
                ('last_read_date', models.DateField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.user')),
            ],
            options={
                'db_table': 'reading_state',
                'ordering': ['reading_state'],
            },
        ),
        migrations.CreateModel(
            name='InteractionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.course')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.user')),
            ],
            options={
                'db_table': 'interaction_history',
                'ordering': ['interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('feedback', models.TextField(max_length=150)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.user')),
            ],
            options={
                'db_table': 'grade',
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.user')),
            ],
            options={
                'db_table': 'enrollment',
                'ordering': ['enrollment_date'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.user'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.course'),
        ),
    ]
