# Generated by Django 4.2.7 on 2023-11-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='document',
            field=models.FileField(default='default.pdf', upload_to='materials/'),
        ),
    ]
